### PR TITLE
feat: allow extra params in save_and_push, push_delta, retrieve

### PR DESCRIPTION
**Pull request by xixiaofinland**

### CODE REVIEW

**Comment by xixiaofinland** [comment]
I tested manually with these hotkeys

```
        local Sf = require("sf")
        vim.keymap.set('n', '<leader>s1', function() Sf.save_and_push() end, { desc = 'test1' })
        vim.keymap.set('n', '<leader>s2', function() Sf.push_delta() end, { desc = 'test2' })
        vim.keymap.set('n', '<leader>s3', function() Sf.retrieve() end, { desc = 'test3' })
        vim.keymap.set('n', '<leader>s4', function() Sf.save_and_push('-c') end, { desc = 'test4' })
        vim.keymap.set('n', '<leader>s5', function() Sf.push_delta('-c') end, { desc = 'test5' })
        vim.keymap.set('n', '<leader>s6', function() Sf.retrieve('-c') end, { desc = 'test6' })
```

**Comment by FedeAbella** [comment]
Should we add it to `retrieve_delta` as well since we're at it?

**Comment by xixiaofinland** [comment]
#251

**Comment by xixiaofinland** [comment]
> Should we add it to `retrieve_delta` as well since we're at it?

done

**Review by FedeAbella — APPROVED** [review]
Looks good! :rocket:

**Comment by xixiaofinland** [comment]
do you have the permisson to merge PR into main? @FedeAbella 
If no, i will figure out and grant you.

**Comment by FedeAbella** [comment]
Merged!

**Pull request merged**
