### PR TITLE
Feat: Add new commands to Term and Test

### PR DESCRIPTION
**Pull request by FedeAbella**
- Add new commands to Term for retrieving an entire manifest package xml file,
    for running a file as anonymous apex, and for running queries in files.
- Add new command to Test to run all local tests in target org

Also creates the user commands for these.

### CODE REVIEW

**Comment by xixiaofinland** [comment]
@FedeAbella  Hi Frederico, thanks for your PR! I was away for a couple of weeks until now.

I'm not so sure what commands to take in as everybody has different needs of SF commands. My original design is to keep the commands bare minimal while allowing the `SF.run()` to accept any sf command the user wants to execute.

For example, you can add your own hotkey to use `Sf.run("sf project retrieve start -x %:p")` to achieve `Term.retrieve_package()` defined in your PR.

**Comment by FedeAbella** [comment]
@xixiaofinland That makes perfect sense. I honestly totally missed `Sf.run` on my checking the code. I thought about adding those that are more commonly exposed in VSCode extensions in the command prompt. Those probably get more use, and would maybe attract more people to try neovim if they see they've got quick access to the same functionalities with out of the box commands.

As a sidenote, I've got a couple more lined up to create Apex Classes and Aura/LWC bundles using `vim.ui.input` to get the names, but didn't want to overwhelm with PRs. If you feel those wouldn't make good additions, let me know.

**Comment by xixiaofinland** [comment]
> @xixiaofinland That makes perfect sense. I honestly totally missed `Sf.run` on my checking the code. I thought about adding those that are more commonly exposed in VSCode extensions in the command prompt. Those probably get more use, and would maybe attract more people to try neovim if they see they've got quick access to the same functionalities with out of the box commands.
> 
> As a sidenote, I've got a couple more lined up to create Apex Classes and Aura/LWC bundles using `vim.ui.input` to get the names, but didn't want to overwhelm with PRs. If you feel those wouldn't make good additions, let me know.

Do the commands of this PR all exist in VSCode? I could use this as a rule of thumb to determine whether to take in new commands.

Creating Apex and Aura/LWC is a welcomed feature, feel free to make the PR. I think the tricky part is to use the file path opened i n the current buffer or the `:pwd` to determine where to locate the new generated files.

**Comment by FedeAbella** [comment]
Oh, yeah, you can get all of these in some form or another via the command palette in VSCode:
- Anonymous Apex:
image

- Run Apex Tests:
image
image

(Maybe at some point in the future selecting a test class to run from `telescope` could be an option, but honestly I'm a fan of KISS, and running it from the file itself looks good enough to me)

- Retrieve Package:
image

- Run Query (with selected text, I personally think running the file is better):
image
(If run with a command that let's you type the query instead, you get the option for tooling queries. I think having you type the entire query in the command palette in VSCode is insane, so again I think the current file is better):
image


I'll prepare a branch with the create apex and lightning bundles, and submit a PR.

**Comment by xixiaofinland** [comment]
> (Maybe at some point in the future selecting a test class to run from `telescope` could be an option, but honestly I'm a fan of KISS, and running it from the file itself looks good enough to me)

Not sure if you are aware, there is already a beta feature (`<leader>so`) to select test methods from the current Apex test file, after which `tt` to use telescope to switch to another test file to continue adding more tests.
This allows to combine tests from various apex test files, but the flow isn't intuitive as I'd like to, but I didn't figure out a better way.

Image 002

**Comment by xixiaofinland** [comment]
@FedeAbella  Thanks for your PRs, both are accepted. I will try them out in dev branch and merge into master once they are stable. Thanks again for the contribution!

**Comment by FedeAbella** [comment]
> Not sure if you are aware, there is already a beta feature (`<leader>so`) to select test methods from the current Apex test file, after which `tt` to use telescope to switch to another test file to continue adding more tests. This allows to combine tests from various apex test files, but the flow isn't intuitive as I'd like to, but I didn't figure out a better way.

I didn't notice that one, but I think the plugin already offers so much between running a method, a file, and now all tests, that you can for sure take your time to find nice flows for the rest.

> Thanks for your PRs, both are accepted. I will try them out in dev branch and merge into master once they are stable. Thanks again for the contribution!

You're welcome! I've got a couple more things in mind. One is for running `jest` tests in lwcs, but I don't feel as comfortable with `treesitter` yet that I can parse your existing functions for identifying a method and a file and use those to run `jest`. I'll keep thinking about it.

After that, I may veer my fork a bit further away due to some other changes being more to suit my own style, or personal preferences, but if I see anything worthwile to contribute to the core functionalities, I'll make another PR. :D

**Comment by xixiaofinland** [comment]
sure, let's keep in touch and share useful tips with each other.

**Pull request merged**
